name: Add a new model/site
description: Suggest a new AI model or website to include in the GreenScore extension
title: "[New Entry] "
labels: ["data-entry", "enhancement"]
body:
  - type: input
    id: site
    attributes:
      label: Website domain
      description: The hostname or domain of the site (e.g. chatgpt.com, claude.ai)
      placeholder: e.g. example.com
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model name
      description: The name of the AI model used on this site
      placeholder: e.g. GPT-4, Claude 3, Gemini 1.5
    validations:
      required: true

  - type: dropdown
    id: energy
    attributes:
      label: Energy usage
      description: Estimated energy usage level
      options:
        - low
        - medium
        - high
        - unknown
    validations:
      required: true

  - type: dropdown
    id: water
    attributes:
      label: Water usage
      description: Estimated water usage level
      options:
        - low
        - medium
        - high
        - unknown
    validations:
      required: true

  - type: dropdown
    id: rating
    attributes:
      label: GreenScore rating
      description: A 0–5 rating of the model’s sustainability (0 = worst, 5 = best)
      options:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
    validations:
      required: true

  - type: textarea
    id: source
    attributes:
      label: Sources or notes
      description: Link to evidence or explain how you determined the data (optional)
      placeholder: e.g. https://arxiv.org/pdf/... or notes about inference
